name: My_first_push
on: 
  push: 

jobs:
  Tarea1:
    runs-on: ubuntu-22.04

    steps:
      - name: Datos del push
        run:  |
          echo "Autor del push ${{ github.event.head_commit.author.name }}"
          echo "Mensaje ${{ github.event.head_commit.message }}"
