name: Hello world
on: 
  workflow_dispatch:

jobs:
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: Di Hola
        run: echo "Hello World Juan Diego Pardo Zamarripa"
        
      - name: Listar carpetas
        run: ls -l
        
      - name: Mostrar fecha del sistema
        run: date
